[package]
name = "puma"
version = "0.0.1"
edition = "2021"
description = "A lightweight, high-performance inference engine for heterogeneous devices."
license = "Apache-2.0"

[dependencies]

clap = { version = "4.5.28", features = ["derive"] }
prettytable-rs = "0.10"
